---
name: "Build Containers"

'on':
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build-containers:
    runs-on: "ubuntu-latest"
    name: "Build and push container images"
    strategy:
      matrix:
        target:
          - src: "demo/app1"
            name: "sample-application"
          - src: "demo/app2"
            name: "demo-application"
    steps:
      - name: "Checkout the code"
        uses: "actions/checkout@v3"

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build container ${{ matrix.target.name }}"
        uses: docker/build-push-action@v2
        with:
          context: "${{ matrix.target.src }}"
          push: true
          tags: "ghcr.io/tbobm/gha-dynamic-containers:${{ matrix.target.name }}-latest"
