---
name: "Build Containers"

'on':
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build-containers:
    runs-on: "ubuntu-latest"
    name: "Build and push container images"
    strategy:
      matrix:
        target:
          - src: "demo/app1"
            name: "sample-application"
          - src: "demo/app2"
            name: "demo-application"
    steps:
      - name: "Checkout the code"
        uses: "actions/checkout@v3"

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Slugify path to create container tag"
        id: slugify-src
        env:
          TARGET_SRC: ${{ matrix.target.src }}
        run: |
          echo "::set-output name=target-slug::$(echo $TARGET_SRC | iconv -t ascii//TRANSLIT | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr A-Z a-z)"

      - name: "Build container ${{ matrix.target.name }}"
        uses: docker/build-push-action@v2
        with:
          context: "${{ matrix.target.src }}"
          push: true
          tags: "ghcr.io/tbobm/gha-dynamic-containers:${{ steps.slugify-src.outputs.target-slug }}-latest"
